(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const K={chats:"ozlind:v5:chats",settings:"ozlind:v5:settings",theme:"ozlind:v1:theme",visitor:"ozlind:v1:visitor"};
const MAX_CHATS=100,MAX_CONTEXT=20,MAX_ATTACH=4,MAX_IMAGE=8*1024*1024;
let chats=load(K.chats,[]),active=chats[0]?.id||null,attachments=[],controller=null,generating=false,editingIndex=null;
let settings={responseLength:"medium",responseStyle:"balanced",memory:true,instructions:"",mode:"auto",...load(K.settings,{})};
function load(k,f){try{const v=localStorage.getItem(k);return v==null?f:JSON.parse(v)}catch{return f}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{toast("Browser storage is full.","error")}}
function uid(){return crypto?.randomUUID?.()||Date.now()+"_"+Math.random().toString(36).slice(2)}
function visitorId(){let v=localStorage.getItem(K.visitor);if(!v){v=uid();try{localStorage.setItem(K.visitor,v)}catch{}}return v}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(msg,type=""){const s=$("#toastStack");if(!s)return;const n=document.createElement("div");n.className="toast "+type;n.textContent=msg;s.append(n);setTimeout(()=>n.remove(),3200)}
function current(){return chats.find(c=>c.id===active)}
function persist(){chats=chats.filter(c=>c?.id&&Array.isArray(c.messages)).sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)).slice(0,MAX_CHATS);save(K.chats,chats)}
function titleFrom(text){let t=String(text||"").replace(/\s+/g," ").trim().replace(/^(hi|hello|hey|hai|good morning|good afternoon|good evening)[,!. ]*/i,"").replace(/^(can you|could you|please|help me|i want to|i need to)\s+/i,"").trim();if(!t)return"New conversation";t=t.length>58?t.slice(0,58)+"…":t;return t.charAt(0).toUpperCase()+t.slice(1)}
function newChat(){if(generating){toast("Stop the current response first.","error");return}const now=new Date().toISOString(),c={id:uid(),title:"New chat",messages:[],createdAt:now,updatedAt:now};chats.unshift(c);active=c.id;attachments=[];editingIndex=null;persist();renderFiles();renderMessages();renderHistory();openPage("chat");setTimeout(()=>$("#chatInput")?.focus(),30)}
function openPage(view){$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const t={chat:"AI Chat",history:"History",research:"Research",vision:"Vision",settings:"Settings"};$("#topbarTitle").textContent=t[view]||"OZLIND";if(view==="history")renderHistory();if(view==="settings")loadSettingsUI();closeSidebar()}
function closeSidebar(){$("#sidebar")?.classList.remove("open");$("#sidebarOverlay")?.classList.remove("open")}
function formatText(text){let s=esc(text);s=s.replace(/```([\s\S]*?)```/g,(_,c)=>`<pre class="code-block"><code>${c.trim()}</code></pre>`);s=s.replace(/\*\*(.*?)\*\*/g,"<strong>$1</strong>");return s.replace(/\n/g,"<br>")}
function renderActions(i,role){return `<div class="message-actions"><button type="button" data-copy="${i}">Copy</button>${role==="user"?`<button type="button" data-edit="${i}">Edit</button>`:`<button type="button" data-regenerate="${i}">Regenerate</button>`}<button type="button" data-delete-message="${i}">Delete</button></div>`}
function renderImages(arr,msgIndex){if(!arr?.length)return"";return `<div class="message-images">${arr.map((x,i)=>`<button class="message-image" type="button" data-image-message="${msgIndex}" data-image="${i}"><img src="${esc(x.dataUrl)}" alt="${esc(x.name||"Uploaded image")}"></button>`).join("")}</div>`}
function renderSources(sources){if(!Array.isArray(sources)||!sources.length)return"";return `<div class="message-sources"><div class="sources-title">Sources</div>${sources.slice(0,5).map((s,i)=>`<a class="source-card" href="${esc(s.url)}" target="_blank" rel="noopener noreferrer"><span>${i+1}</span><strong>${esc(s.title||s.url)}</strong><small>${esc(s.domain||"")}</small></a>`).join("")}</div>`}
function renderMessages(){const box=$("#chatMessages"),empty=$("#chatEmpty"),c=current();if(!box||!empty)return;box.innerHTML="";if(!c?.messages?.length){empty.classList.remove("hidden");return}empty.classList.add("hidden");c.messages.forEach((m,i)=>{const a=document.createElement("article");a.className=`message ${m.role}${m.error?" error":""}`;let body=m.pending?`<div class="typing-indicator"><span></span><span></span><span></span></div>`:m.content?`<div class="message-body">${formatText(m.content)}</div>`:"";a.innerHTML=`<div class="message-meta">${m.role==="user"?"You":"OZLIND AI"}</div>${body}${m.role==="user"?renderImages(m.attachments,i):""}${m.sources?renderSources(m.sources):""}${!m.pending&&!m.error?renderActions(i,m.role):""}`;box.appendChild(a)});requestAnimationFrame(()=>{$("#chatScroll")?.scrollTo({top:$("#chatScroll").scrollHeight,behavior:"smooth"})})}
function renderHistory(filter=""){const box=$("#conversationList");if(!box)return;const q=filter.toLowerCase().trim(),rows=chats.filter(c=>(c.title+" "+c.messages.map(m=>m.content||"").join(" ")).toLowerCase().includes(q));box.innerHTML=rows.length?rows.map(c=>`<div class="history-item"><div class="history-main"><b>${esc(c.title)}</b><small>${c.messages.length} message${c.messages.length===1?"":"s"}</small></div><div><button class="small-action" data-open="${esc(c.id)}">Open</button> <button class="small-action danger" data-delete-chat="${esc(c.id)}">Delete</button></div></div>`).join(""):`<div class="history-empty">No conversations found.</div>`}
function resize(){const i=$("#chatInput");if(i){i.style.height="auto";i.style.height=Math.min(i.scrollHeight,180)+"px"}}
function renderFiles(){const b=$("#chatAttachments");if(!b)return;b.innerHTML=attachments.map((f,i)=>`<div class="attachment"><img src="${esc(f.dataUrl)}" alt="${esc(f.name)}"><button type="button" data-remove-file="${i}">×</button></div>`).join("");$("#contextIndicator").textContent=attachments.length?`${attachments.length} image${attachments.length>1?"s":""} attached`:editingIndex!==null?"Editing message":"Ready"}
function readImage(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
async function addFiles(list){for(const f of [...list].slice(0,MAX_ATTACH-attachments.length)){if(!f.type.startsWith("image/")){toast("Only image files are supported.","error");continue}if(f.size>MAX_IMAGE){toast("Each image must be under 8MB.","error");continue}try{attachments.push({name:f.name,type:f.type,size:f.size,dataUrl:await readImage(f)})}catch{toast("Could not read that image.","error")}}renderFiles()}
function payloadMessages(c){let ms=(c?.messages||[]).filter(m=>["user","assistant"].includes(m.role));ms=settings.memory?ms.slice(-MAX_CONTEXT):ms.slice(-1);return ms.map(m=>m.role==="user"&&m.attachments?.length?{role:"user",content:[{type:"text",text:m.content||""},...m.attachments.map(x=>({type:"image_url",image_url:{url:x.dataUrl}}))]}:{role:m.role,content:m.content||""})}
function setBusy(v){generating=v;$("#sendBtn")?.classList.toggle("hidden",v);$("#stopBtn")?.classList.toggle("hidden",!v);const s=$("#connectionStatus");if(s){s.innerHTML=`<i></i><span>${v?"Generating…":"Ready"}</span>`;s.classList.toggle("is-busy",v)}}
function classifyError(e){if(e?.name==="AbortError")return"Generation stopped.";if(!navigator.onLine)return"No internet connection. Please reconnect and try again.";const m=String(e?.message||"");if(/401|403|not configured/i.test(m))return"AI service is not configured correctly. Please check the server settings.";if(/429|rate limit|too many/i.test(m))return"The AI service is busy right now. Please try again in a moment.";if(/408|timeout|timed out/i.test(m))return"The request timed out. Please try again.";if(/5\d\d|temporarily unavailable/i.test(m))return"The AI service is temporarily unavailable. Please try again.";return m||"Unable to complete the request."}
async function send(){if(generating)return;const input=$("#chatInput"),text=input.value.trim();if(!text&&!attachments.length)return;let c=current();if(!c){newChat();c=current()}
  if(editingIndex!==null){const old=c.messages[editingIndex];if(!old||old.role!=="user"){editingIndex=null}else{old.content=text;old.attachments=[...attachments];c.messages.splice(editingIndex+1);editingIndex=null;attachments=[];c.title=titleFrom(text||"Image analysis");c.updatedAt=new Date().toISOString();persist();input.value="";resize();renderFiles();renderMessages();await generate(c);return}}
  const imgs=attachments.splice(0);renderFiles();const user={role:"user",content:text,attachments:imgs};c.messages.push(user);if(c.messages.length===1)c.title=titleFrom(text||"Image analysis");c.updatedAt=new Date().toISOString();persist();input.value="";resize();renderMessages();await generate(c)}
async function generate(c){const a={role:"assistant",content:"",pending:true};c.messages.push(a);setBusy(true);controller=new AbortController();persist();renderMessages();try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json","Accept":"text/event-stream"},signal:controller.signal,body:JSON.stringify({messages:payloadMessages(c),model:$("#modelSelect").value,research:$("#researchToggle").getAttribute("aria-pressed")==="true",responseLength:settings.responseLength,responseStyle:settings.responseStyle,memory:settings.memory,customInstructions:settings.instructions,visitorId:visitorId(),conversationId:c.serverConversationId||null,title:c.title})});if(!r.ok){let msg=`Request failed (${r.status}).`;try{const d=await r.json();if(d.error)msg=d.error}catch{}throw Error(msg)}if(!r.body)throw Error("No response returned.");const rd=r.body.getReader(),dec=new TextDecoder();let buf="";for(;;){const {value,done}=await rd.read();if(done)break;buf+=dec.decode(value,{stream:true});const lines=buf.split(/\r?\n/);buf=lines.pop()||"";for(const line of lines){if(!line.startsWith("data:"))continue;const raw=line.slice(5).trim();if(!raw||raw==="[DONE]")continue;let d;try{d=JSON.parse(raw)}catch{continue}if(d.type==="conversation")c.serverConversationId=d.conversationId;if(d.type==="provider")a.provider=d.provider;if(d.type==="sources")a.sources=Array.isArray(d.sources)?d.sources:[];if(d.type==="delta"){a.pending=false;a.content+=d.content||"";renderMessages()}if(d.type==="error")throw Error(d.error||"Generation failed.")}}if(!a.content.trim())throw Error("OZLIND returned an empty response.")}catch(e){if(e.name==="AbortError"){a.content=a.content.trim()?a.content+"\n\nGeneration stopped.":"Generation stopped."}else{a.error=true;a.content=classifyError(e);toast(a.content,"error")}}finally{delete a.pending;c.updatedAt=new Date().toISOString();persist();renderMessages();setBusy(false);controller=null}}
function toggleTheme(){const n=document.body.dataset.theme==="dark"?"light":"dark";document.body.dataset.theme=n;save(K.theme,n);$("#themeToggle").textContent=n==="dark"?"☾":"☀"}
function loadSettingsUI(){$("#responseLength").value=settings.responseLength;$("#responseStyle").value=settings.responseStyle;$("#customInstructions").value=settings.instructions||"";$("#memoryToggle").setAttribute("aria-pressed",String(settings.memory));$("#modelSelect").value=settings.mode||"auto"}
function saveSettings(){settings.responseLength=$("#responseLength").value;settings.responseStyle=$("#responseStyle").value;settings.instructions=$("#customInstructions").value.trim();save(K.settings,settings);toast("Settings saved.","ok")}
function init(){document.body.dataset.theme=load(K.theme,"dark")==="light"?"light":"dark";$("#themeToggle").textContent=document.body.dataset.theme==="dark"?"☾":"☀";if(!chats.length){const now=new Date().toISOString();const c={id:uid(),title:"New chat",messages:[],createdAt:now,updatedAt:now};chats=[c];active=c.id;persist()}loadSettingsUI();renderFiles();renderMessages();renderHistory()}
document.addEventListener("click",async e=>{const nav=e.target.closest("[data-view]");if(nav)return openPage(nav.dataset.view);if(e.target.closest("#newChatBtn"))return newChat();if(e.target.closest("#themeToggle"))return toggleTheme();if(e.target.closest("#mobileNavBtn")){$("#sidebar").classList.add("open");$("#sidebarOverlay").classList.add("open");return}if(e.target.closest("#sidebarClose")||e.target.closest("#sidebarOverlay"))return closeSidebar();const p=e.target.closest("[data-prompt]");if(p){openPage("chat");$("#chatInput").value=p.dataset.prompt;resize();$("#chatInput").focus();return}if(e.target.closest("[data-go-chat]"))return openPage("chat");const rm=e.target.closest("[data-remove-file]");if(rm){attachments.splice(+rm.dataset.removeFile,1);renderFiles();return}const op=e.target.closest("[data-open]");if(op){active=op.dataset.open;renderMessages();openPage("chat");return}const dc=e.target.closest("[data-delete-chat]");if(dc){if(confirm("Delete this conversation?")){chats=chats.filter(c=>c.id!==dc.dataset.deleteChat);if(active===dc.dataset.deleteChat)active=chats[0]?.id||null;persist();renderHistory();renderMessages()}return}const cp=e.target.closest("[data-copy]");if(cp){const m=current()?.messages[+cp.dataset.copy];if(m){navigator.clipboard?.writeText(m.content||"").then(()=>toast("Copied.","ok")).catch(()=>toast("Copy unavailable. Select and copy the text manually.","error"))}return}
  const ed=e.target.closest("[data-edit]");if(ed){const c=current(),i=+ed.dataset.edit,m=c?.messages[i];if(m?.role==="user"&&!generating){editingIndex=i;$("#chatInput").value=m.content||"";attachments=m.attachments?[...m.attachments]:[];renderFiles();resize();openPage("chat");$("#chatInput").focus();toast("Edit the message, then send. Original is kept until you send.");}return}
  const del=e.target.closest("[data-delete-message]");if(del){const c=current();if(c&&confirm("Delete this message?")){c.messages.splice(+del.dataset.deleteMessage,1);persist();renderMessages()}return}
  const reg=e.target.closest("[data-regenerate]");if(reg){const c=current(),i=+reg.dataset.regenerate;if(c&&!generating&&c.messages[i]?.role==="assistant"){c.messages.splice(i,1);persist();generate(c)}return}
  const img=e.target.closest("[data-image-message]");if(img){const c=current(),m=c?.messages[+img.dataset.imageMessage],x=m?.attachments?.[+img.dataset.image];if(x)window.open(x.dataUrl,"_blank");return}
});
$("#chatForm").addEventListener("submit",e=>{e.preventDefault();send()});$("#chatInput").addEventListener("input",resize);$("#chatInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}});$("#attachBtn").addEventListener("click",()=>$("#fileInput").click());$("#fileInput").addEventListener("change",e=>{addFiles(e.target.files);e.target.value=""});$("#stopBtn").addEventListener("click",()=>controller?.abort());$("#researchToggle").addEventListener("click",e=>{const b=e.currentTarget,on=b.getAttribute("aria-pressed")==="true";b.setAttribute("aria-pressed",String(!on));b.querySelector("em").textContent=!on?"ON":"OFF"});$("#modelSelect").addEventListener("change",e=>{settings.mode=e.target.value;save(K.settings,settings)});$("#memoryToggle").addEventListener("click",e=>{settings.memory=!settings.memory;e.currentTarget.setAttribute("aria-pressed",String(settings.memory));save(K.settings,settings)});$("#saveInstructionsBtn").addEventListener("click",saveSettings);$("#responseLength").addEventListener("change",saveSettings);$("#responseStyle").addEventListener("change",saveSettings);$("#conversationSearch").addEventListener("input",e=>renderHistory(e.target.value));$("#exportHistoryBtn").addEventListener("click",()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({version:5,chats},null,2)],{type:"application/json"}));a.download="ozlind-history.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});$("#importHistoryBtn").addEventListener("click",()=>$("#historyFileInput").click());$("#historyFileInput").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),incoming=Array.isArray(d)?d:d.chats;if(!Array.isArray(incoming))throw Error();chats=[...incoming.filter(c=>c?.id&&Array.isArray(c.messages)),...chats];active=chats[0]?.id||null;persist();renderHistory();renderMessages();toast("History imported.","ok")}catch{toast("Invalid history file.","error")}};r.readAsText(f);e.target.value=""});$("#clearHistoryBtn").addEventListener("click",()=>{if(!confirm("Clear all local conversation history?"))return;chats=[];active=null;newChat()});
init();
})();
