"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";
import {Button} from "@/components/ui/Button";
import {OfflineBanner} from "@/components/chat/OfflineBanner";
import {MarkdownRenderer} from "@/components/chat/MarkdownRenderer";
import {usePreferences} from "@/hooks/usePreferences";
import {OzlindIcon} from "@/components/ui/OzlindIcon";

type Message={id:string;role:"user"|"assistant";content:string;status?:string};

export function Chat({conversationId:initialId}:{conversationId?:string}){
 const router=useRouter(); const[id,setId]=useState(initialId); const[messages,setMessages]=useState<Message[]>([]); const[draft,setDraft]=useState(""); const{preferences}=usePreferences(); const[model,setModel]=useState(preferences.default_model); const[streaming,setStreaming]=useState(false); const[error,setError]=useState(""); const[online,setOnline]=useState(true); const abortRef=useRef<AbortController|null>(null); const scrollRef=useRef<HTMLDivElement>(null); const stick=useRef(true); const textareaRef=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>setModel(preferences.default_model),[preferences.default_model]);
 useEffect(()=>{const onPrompt=(e:Event)=>setDraft((e as CustomEvent<string>).detail);const sync=()=>setOnline(navigator.onLine);sync();addEventListener("ozlind:prompt",onPrompt);addEventListener("online",sync);addEventListener("offline",sync);return()=>{removeEventListener("ozlind:prompt",onPrompt);removeEventListener("online",sync);removeEventListener("offline",sync)}},[]);
 useEffect(()=>{let live=true;(async()=>{if(!id){setMessages([]);return}try{const supabase=createClient();const{data,error}=await supabase.from("messages").select("id,role,content,status").eq("conversation_id",id).order("created_at",{ascending:true});if(live){if(error)setError("Could not load this conversation.");setMessages((data??[]) as Message[])}}catch{if(live)setError("Could not load this conversation.")}})();return()=>{live=false}},[id]);
 useEffect(()=>{if(stick.current&&preferences.auto_scroll)scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:streaming?"auto":"smooth"})},[messages,streaming,preferences.auto_scroll]);
 useEffect(()=>{const el=textareaRef.current;if(el){el.style.height="auto";el.style.height=Math.min(el.scrollHeight,200)+"px"}},[draft]);
 async function send(action:"send"|"regenerate"="send",contentOverride?:string){const content=(contentOverride??draft).trim();if((action==="send"&&!content)||streaming||!online)return;if(action==="send")setDraft("");setError("");const key=crypto.randomUUID(),assistantId=crypto.randomUUID();if(action==="send")setMessages(v=>v.concat({id:key,role:"user",content,status:"complete"}));setMessages(v=>v.concat({id:assistantId,role:"assistant",content:"",status:"streaming"}));setStreaming(true);const controller=new AbortController();abortRef.current=controller;try{const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:id,content,model,action,idempotencyKey:key,research:preferences.research_enabled}),signal:controller.signal});if(response.status===204){const duplicateConversationId=response.headers.get("X-OZLIND-Conversation-ID");setMessages(v=>v.filter(m=>m.id!==key&&m.id!==assistantId));if(duplicateConversationId){setId(duplicateConversationId);router.replace("/app/"+duplicateConversationId)}return}if(!response.ok){const body=await response.json().catch(()=>null);if(body?.error?.code==="AUTH_REQUIRED")router.replace("/login");throw new Error(body?.error?.message||"Ozlind could not generate a response.")}const nextId=response.headers.get("X-OZLIND-Conversation-ID");if(!id&&nextId){setId(nextId);router.replace("/app/"+nextId)}const reader=response.body?.getReader();if(!reader)throw new Error("Streaming response unavailable.");const decoder=new TextDecoder();for(;;){const part=await reader.read();if(part.done)break;const delta=decoder.decode(part.value,{stream:true});setMessages(v=>v.map(m=>m.id===assistantId?{...m,content:m.content+delta,status:"streaming"}:m))}setMessages(v=>v.map(m=>m.id===assistantId?{...m,status:"complete"}:m))}catch(e){if(controller.signal.aborted)setMessages(v=>v.map(m=>m.id===assistantId?{...m,status:"interrupted"}:m));else{setError(e instanceof Error?e.message:"Generation failed.");setMessages(v=>v.filter(m=>m.id!==assistantId))}}finally{abortRef.current=null;setStreaming(false)}}
 const handleKey=(e:React.KeyboardEvent)=>{if(e.key==="Enter"&&!e.shiftKey&&preferences.enter_to_send){e.preventDefault();send()}};
 return <main className="chat-page"><OfflineBanner/><header className="chat-header"><div><p className="eyebrow">Workspace</p><h2>{id?"Conversation":"New chat"}</h2></div></header><div ref={scrollRef} className="message-list" onScroll={e=>{const el=e.currentTarget;stick.current=el.scrollTop+el.clientHeight>=el.scrollHeight-40}} role="log" aria-live="polite"><div className="message-column">{messages.length===0?<div className="empty-chat"><span className="empty-chat-mark" aria-hidden="true"><OzlindIcon name="ozl-mark" size={42}/></span><h1>How can I help?</h1><p>Ask a question, draft something, or work through a problem.</p><div className="prompt-grid"><button onClick={()=>setDraft("Help me plan my week.")}>Plan my week</button><button onClick={()=>setDraft("Explain a difficult idea simply.")}>Explain an idea</button><button onClick={()=>setDraft("Help me write something clearly.")}>Write with me</button></div></div>:messages.map(m=><article key={m.id} className={"message "+m.role}><div className="message-role">{m.role==="user"?"You":"Ozlind"}</div><div className="message-content">{m.role==="user"?<p>{m.content}</p>:<MarkdownRenderer content={m.content||" "}/>}</div>{m.status==="interrupted"&&<div className="interrupted">Generation interrupted. <button onClick={()=>send("regenerate",messages.filter(x=>x.role==="user").at(-1)?.content)}>Continue</button></div>}{m.role==="assistant"&&m.status==="streaming"&&<span className="stream-cursor"/>}</article>)}</div></div>{error&&<div className="error-card" role="alert"><span>{error}</span><button onClick={()=>setError("")}>Dismiss</button></div>}<div className="composer-wrap"><div className="composer"><select value={model} onChange={e=>setModel(e.target.value)} aria-label="Model"><option value="groq:llama-3.3-70b-versatile">Llama 3.3 70B</option><option value="groq:deepseek-r1-distill-llama-70b">DeepThink</option><option value="google:gemini-2.0-flash">Gemini Flash</option></select><textarea ref={textareaRef} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={handleKey} rows={1} maxLength={20000} placeholder="Message Ozlind…"/><Button className="send-button" disabled={!online} onClick={()=>streaming?abortRef.current?.abort():send()} aria-label={streaming?"Stop generation":"Send message"}>{streaming?<><OzlindIcon name="i-stop" size={18}/>Stop</>:<><OzlindIcon name="i-arrow-up" size={18}/>Send</>}</Button></div><p className="composer-note">Ozlind can make mistakes. Verify important information.</p></div></main>;
}