-- Reconcile the repository schema with the live production chat schema.
-- Idempotent: safe when the target objects already exist.

create table if not exists public.usage_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete set null,
  mode text,
  provider text,
  model text,
  tokens_in integer,
  tokens_out integer,
  latency_ms integer,
  ok boolean not null default true,
  error text,
  created_at timestamptz not null default now()
);

alter table public.usage_logs enable row level security;

drop policy if exists "ozlind_usage_logs_insert" on public.usage_logs;
create policy "ozlind_usage_logs_insert"
on public.usage_logs for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "ozlind_usage_logs_select" on public.usage_logs;
create policy "ozlind_usage_logs_select"
on public.usage_logs for select to authenticated
using ((select auth.uid()) = user_id or (select public.is_admin()));

create index if not exists usage_logs_user_created_idx
on public.usage_logs (user_id, created_at desc);

create index if not exists usage_logs_conversation_id_idx
on public.usage_logs (conversation_id);

alter table public.messages add column if not exists model text;
alter table public.messages add column if not exists mode text;
alter table public.messages add column if not exists feedback smallint;
alter table public.messages add column if not exists tokens_in integer;
alter table public.messages add column if not exists tokens_out integer;
alter table public.messages add column if not exists edited_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_attribute
    where attrelid = 'public.messages'::regclass
      and attname = 'search'
      and not attisdropped
  ) then
    alter table public.messages
      add column search tsvector generated always as (
        to_tsvector('simple'::regconfig, coalesce(content, ''))
      ) stored;
  end if;
end
$$;

create index if not exists messages_search_idx
on public.messages using gin (search);
